// Initial default mock services to make PulseBoard populated immediately
export const INITIAL_SERVICES = [
  {
    id: 'srv-auth',
    name: 'Authentication API',
    url: 'https://auth.internal.corp/v1/health',
    method: 'GET',
    expectedStatus: 200,
    mode: 'mock',
    status: 'operational',
    responseTime: 42,
    lastChecked: new Date(Date.now() - 1000 * 45).toISOString(),
    history: [
      { time: 48, status: 'operational' },
      { time: 52, status: 'operational' },
      { time: 45, status: 'operational' },
      { time: 41, status: 'operational' },
      { time: 44, status: 'operational' },
      { time: 39, status: 'operational' },
      { time: 42, status: 'operational' },
    ],
  },
  {
    id: 'srv-payment',
    name: 'Payment Processing Gateway',
    url: 'https://api.payment-mock.com/v1/ping',
    method: 'GET',
    expectedStatus: 200,
    mode: 'mock',
    status: 'operational',
    responseTime: 135,
    lastChecked: new Date(Date.now() - 1000 * 120).toISOString(),
    history: [
      { time: 140, status: 'operational' },
      { time: 155, status: 'operational' },
      { time: 128, status: 'operational' },
      { time: 160, status: 'operational' },
      { time: 142, status: 'operational' },
      { time: 130, status: 'operational' },
      { time: 135, status: 'operational' },
    ],
  },
  {
    id: 'srv-notifications',
    name: 'Notification Delivery Service',
    url: 'https://push.internal.corp/status',
    method: 'GET',
    expectedStatus: 200,
    mode: 'mock',
    status: 'degraded',
    responseTime: 910,
    lastChecked: new Date(Date.now() - 1000 * 80).toISOString(),
    history: [
      { time: 320, status: 'operational' },
      { time: 540, status: 'operational' },
      { time: 780, status: 'operational' },
      { time: 860, status: 'degraded' },
      { time: 940, status: 'degraded' },
      { time: 890, status: 'degraded' },
      { time: 910, status: 'degraded' },
    ],
  },
  {
    id: 'srv-storage',
    name: 'Cloud Asset Storage API',
    url: 'https://assets.storage-mock.internal/healthz',
    method: 'GET',
    expectedStatus: 200,
    mode: 'mock',
    status: 'operational',
    responseTime: 68,
    lastChecked: new Date(Date.now() - 1000 * 30).toISOString(),
    history: [
      { time: 72, status: 'operational' },
      { time: 65, status: 'operational' },
      { time: 70, status: 'operational' },
      { time: 64, status: 'operational' },
      { time: 80, status: 'operational' },
      { time: 71, status: 'operational' },
      { time: 68, status: 'operational' },
    ],
  },
];
